version: '3.8'

services:
  # Combined Ollama and tRNA UI in a single container
  trna-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trna-service
    ports:
      - "11860:7860"  # Map container port 7860 to host port 11860
    volumes:
      - /data/scratch/larbales/trna-data:/data  # Application data
      - /data/scratch/larbales/ollama-data:/root/.ollama  # Ollama models persistent storage
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    restart: unless-stopped